apiVersion: v1
kind: Pod
metadata:
  name: redpajama-processor
spec:
  containers:
  - name: redpajama-curator
    image: 058264135704.dkr.ecr.us-east-2.amazonaws.com/redpajama-curator:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      limits:
        nvidia.com/gpu: "8"
    volumeMounts:
    - name: s3-data
      mountPath: /data
      readOnly: true
    - name: processing-dir
      mountPath: /processing
  volumes:
  - name: s3-data
    persistentVolumeClaim:
      claimName: redpajama-s3-pvc
  - name: processing-dir
    emptyDir:
      sizeLimit: 1Ti
