apiVersion: v1
kind: PersistentVolume
metadata:
  name: redpajama-s3-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1200Gi
  storageClassName: ""
  claimRef:
    namespace: default
    name: redpajama-s3-pvc
  mountOptions:
    - region us-east-2
    - allow-delete false
    - read-only
  csi:
    driver: s3.csi.aws.com
    volumeHandle: redpajama-s3-volume
    volumeAttributes:
      bucketName: redpajama-v2-bucket
      # Path to RedPajama data within bucket
      prefixPath: redpajama-v2/en
      
      # Use the pod's IAM role for authentication
      authenticationSource: pod
      
      # Set cache for better performance
      cache: emptyDir
      cacheEmptyDirSizeLimit: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpajama-s3-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: redpajama-s3-pv
