apiVersion: v1
kind: Pod
metadata:
  name: redpajama-processor
spec:
  containers:
  - name: redpajama-curator
    image: 058264135704.dkr.ecr.us-west-2.amazonaws.com/sagemaker-nemo-curator:latest
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        nvidia.com/gpu: 8
        vpc.amazonaws.com/efa: 32
      limits:
        nvidia.com/gpu: 8
        vpc.amazonaws.com/efa: 32
    volumeMounts:
    - name: s3-data
      mountPath: /s3
      readOnly: true
    - name: processing-dir
      mountPath: /processing
    - name: fsx-storage
      mountPath: /data
  volumes:
  - name: fsx-storage
    persistentVolumeClaim:
      claimName: correct-subnet-fsx-claim
  - name: s3-data
    persistentVolumeClaim:
      claimName: redpajama-s3-pvc
  - name: processing-dir
    emptyDir:
      sizeLimit: "2000Gi"
