apiVersion: v1
kind: PersistentVolume
metadata:
  name: redpajama-s3-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: s3.csi.aws.com
    volumeHandle: redpajama-s3-volume
    volumeAttributes:
      bucketName: redpajama-v2-bucket
      prefixPath: redpajama-v2/en
      readOnly: "true"
      region: "us-east-2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpajama-s3-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1200Gi
  volumeName: redpajama-s3-pv
  storageClassName: ""
