# redpajama-test-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpajama-curator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpajama-curator
  template:
    metadata:
      labels:
        app: redpajama-curator
    spec:
      containers:
      - name: redpajama-curator
        image: redpajama-curator-sagemaker:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - infinity
        ports:
        - containerPort: 8787
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "8"
        securityContext:
          privileged: true
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0,1,2,3,4,5,6,7"
        - name: PYTHONPATH
          value: "/opt/ml/code"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
