apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"triton-server","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"triton-server"}},"template":{"metadata":{"labels":{"app":"triton-server"}},"spec":{"containers":[{"command":["sleep","infinity"],"image":"nvcr.io/nvidia/tritonserver:25.01-trtllm-python-py3","name":"triton-server","ports":[{"containerPort":8000},{"containerPort":8001},{"containerPort":8002}],"resources":{"limits":{"nvidia.com/gpu":1}},"securityContext":{"privileged":true}}]}}}}
  creationTimestamp: "2025-07-04T19:52:50Z"
  generation: 1
  name: triton-server
  namespace: default
  resourceVersion: "34710044"
  uid: 3e7d24b8-925f-4080-b4a8-17db2aeb20f9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triton-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triton-server
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: nvcr.io/nvidia/tritonserver:25.01-trtllm-python-py3
        imagePullPolicy: IfNotPresent
        name: triton-server
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8002
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-04T19:52:50Z"
    lastUpdateTime: "2025-07-04T19:55:55Z"
    message: ReplicaSet "triton-server-5fcf5c9d6f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-08T14:46:46Z"
    lastUpdateTime: "2025-07-08T14:46:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
