apiVersion: v1
kind: PersistentVolume
metadata:
  name: correct-subnet-fsx-pv
spec:
  capacity:
    storage: 2400Gi  # Match the size of your FSx
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: correct-subnet-fsx-sc
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0a8d4cf33a5d9c4a2
    volumeAttributes:
      dnsname: fs-0a8d4cf33a5d9c4a2.fsx.us-east-2.amazonaws.com
      mountname: ifq6tbev
